# Generated by Django 2.2.5 on 2022-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200815_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='county',
            field=models.CharField(choices=[('Yssyk-Kol', 'Yssyk-Kol'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Batken', 'Batken'), ('Osh', 'Osh'), ('Jalalabad', 'Jalalabad'), ('Bishkek', 'Bishkek'), ('Chui', 'Chui')], default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='town',
            field=models.CharField(choices=[('Tokmok', 'Tokmok'), ('Balykchi', 'Balykchi'), ('Kant', 'Kant'), ('Karakol', 'Karakol'), ('Kara-Balta', 'Kara-Balta'), ('Toktogul', 'Toktogul'), ('Cholpon-Ata', 'Cholpon-Ata'), ('Uzgen', 'Uzgen'), ('Suzak', 'Suzak'), ('Kochkorka', 'Kochkorka'), ('Ala-Archa', 'Ala-Archa'), ('Too-Ashu', 'Too-Ashu'), ('Manas', 'Manas'), ('Ivanovka', 'Ivanovka'), ('Kochkor-Ata', 'Kochkor-Ata'), ('Sahalin', 'Sahalin')], default='Thika', max_length=100),
        ),
    ]
